#!/bin/sh

touch /etc/crontabs/root

uci set luci.main.lang=zh_cn
#设置默认主题
uci set luci.main.mediaurlbase='/luci-static/bootstrap'
uci commit luci

uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci set system.ntp=timeserver
uci set system.ntp.server='cn.pool.ntp.org'
uci set system.ntp.enable_server='1'
uci commit system

uci set fstab.@global[0].anon_mount=1
uci commit fstab

ln -sf /sbin/ip /usr/bin/ip

sed -i '/lienol/d' /etc/opkg/distfeeds.conf
sed -i '/other/d' /etc/opkg/distfeeds.conf
sed -i "s/# //g" /etc/opkg/distfeeds.conf

# set dhcp only once at first boot after install
if [[ ! $(uci show dhcp._set_done) ]]; then
  uci delete dhcp.lan.ra
  uci delete dhcp.lan.dhcpv6
  uci delete dhcp.lan.ndp
  uci set dhcp.lan=dhcp
  uci set dhcp.lan.interface='lan'
  uci set dhcp.lan.ignore='1'
  uci set dhcp.wan=dhcp
  uci set dhcp.wan.interface='wan'
  uci set dhcp.wan.ignore='1'
  uci set dhcp._set_done='1'
  uci commit dhcp
fi

# set network only once at first boot after install
if [[ ! $(uci show network.lan._set_done) ]]; then
  uci delete network.lan
  uci set network.lan=interface
  uci set network.lan._orig_ifname='eth0'
  uci set network.lan._orig_bridge='false'
  uci set network.lan.device='eth0'
  uci set network.lan.proto='dhcp'
  uci set network.lan.ip6assign='64'
  uci set network.lan._set_done='1'
  uci commit network
fi

sed -i '/option disabled/d' /etc/config/wireless
sed -i '/set wireless.radio${devidx}.disabled/d' /lib/wifi/mac80211.sh
wifi up

sed -i 's#openwrt/luci#lienol/openwrt-luci#g' /usr/lib/lua/luci/view/themes/*/footer.htm

#禁用某些可能会自启动且用不上的依赖包服务
/etc/init.d/php7-fastcgi disable 2>/dev/null
/etc/init.d/php7-fpm disable 2>/dev/null
/etc/init.d/php8-fastcgi disable 2>/dev/null
/etc/init.d/php8-fpm disable 2>/dev/null
/etc/init.d/softethervpnbridge disable 2>/dev/null
/etc/init.d/softethervpnserver disable 2>/dev/null
/etc/init.d/softethervpnclient disable 2>/dev/null
/etc/init.d/haproxy disable 2>/dev/null
/etc/init.d/kcptun disable 2>/dev/null

chmod 0755 /etc/init.d/*

rm -rf /tmp/luci-*cache

sed -i '/BUILD_ID=/d' /usr/lib/os-release
sed -i '/DISTRIB_REVISION=/d' /etc/openwrt_release
sed -i '/DISTRIB_DESCRIPTION=/d' /etc/openwrt_release
